### ISSUE TITLE
ngx-extractor issue

### ISSUE THREAD

**Issue by axtho** [ngx-translate/i18n-polyfill#9] opened 2018-01-05 12:33 UTC
there are two issues I am facing:

1. somehow I cannot call ngx-extractor directly, I have to prefix it with node and path-to-bin
2. it works using a string, but if do something like the following, it breaks with the below error:

```TS
export class ViewComponent implements OnDestroy {
    private _alive: boolean = true;

    routes: Object[] = [
        {
            title: this.i18n({value: 'Dashboard', id: 'menu.dashboard'}),
            route: '/dashboard',
            icon: 'dashboard'
        },
```
The error produced by `node node_modules/.bin/ngx-extractor -i "src/**/*.ts" -f xlf -o "src/i18n/messages.xlf"`:
```
SKIP: Unknown argument type: 'ObjectLiteralExpression' NodeObject {
  pos: 1044,
  end: 1086,
  flags: 0,
  transformFlags: undefined,
  parent: undefined,
  kind: 178,
  properties: 
   [ NodeObject {
       pos: 1045,
       end: 1063,
       flags: 0,
       transformFlags: undefined,
       parent: undefined,
       kind: 261,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [TokenObject],
       _children: [Array] },
     NodeObject {
       pos: 1064,
       end: 1085,
       flags: 0,
       transformFlags: undefined,
       parent: undefined,
       kind: 261,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [TokenObject],
       _children: [Array] },
     pos: 1045,
     end: 1085 ],
  _children: 
   [ TokenObject { pos: 1044, end: 1045, flags: 0, parent: [Circular], kind: 17 },
     NodeObject {
       pos: 1045,
       end: 1085,
       flags: 0,
       transformFlags: undefined,
       parent: [Circular],
       kind: 286,
       _children: [Array] },
     TokenObject { pos: 1085, end: 1086, flags: 0, parent: [Circular], kind: 18 } ] }
SKIP: Unknown argument type: 'ObjectLiteralExpression' NodeObject {
  pos: 1202,
  end: 1238,
  flags: 0,
  transformFlags: undefined,
  parent: undefined,
  kind: 178,
  properties: 
   [ NodeObject {
       pos: 1203,
       end: 1218,
       flags: 0,
       transformFlags: undefined,
       parent: undefined,
       kind: 261,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [TokenObject],
       _children: [Array] },
     NodeObject {
       pos: 1219,
       end: 1237,
       flags: 0,
       transformFlags: undefined,
       parent: undefined,
       kind: 261,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [TokenObject],
       _children: [Array] },
     pos: 1203,
     end: 1237 ],
  _children: 
   [ TokenObject { pos: 1202, end: 1203, flags: 0, parent: [Circular], kind: 17 },
     NodeObject {
       pos: 1203,
       end: 1237,
       flags: 0,
       transformFlags: undefined,
       parent: [Circular],
       kind: 286,
       _children: [Array] },
     TokenObject { pos: 1237, end: 1238, flags: 0, parent: [Circular], kind: 18 } ] }
SKIP: Unknown argument type: 'ObjectLiteralExpression' NodeObject {
  pos: 1605,
  end: 1645,
  flags: 0,
  transformFlags: undefined,
  parent: undefined,
  kind: 178,
  properties: 
   [ NodeObject {
       pos: 1606,
       end: 1623,
       flags: 0,
       transformFlags: undefined,
       parent: undefined,
       kind: 261,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [TokenObject],
       _children: [Array] },
     NodeObject {
       pos: 1624,
       end: 1644,
       flags: 0,
       transformFlags: undefined,
       parent: undefined,
       kind: 261,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [TokenObject],
       _children: [Array] },
     pos: 1606,
     end: 1644 ],
  _children: 
   [ TokenObject { pos: 1605, end: 1606, flags: 0, parent: [Circular], kind: 17 },
     NodeObject {
       pos: 1606,
       end: 1644,
       flags: 0,
       transformFlags: undefined,
       parent: [Circular],
       kind: 286,
       _children: [Array] },
     TokenObject { pos: 1644, end: 1645, flags: 0, parent: [Circular], kind: 18 } ] }
```

  EDIT:
Node version 9.3

**Comment by ocombe** [comment] 2018-01-05 13:13
1/ what is your OS? I've only tested on Windows, and some users have reported that it works on Mac.

2/ this feels like a bug in the extractor, working with AST is hard :) I'll try with your example

**Comment by ocombe** [comment] 2018-01-05 13:23
Yes, confirmed that it's a bug in the extractor, fixing it.

**Comment by ocombe** [comment] 2018-01-05 14:46
Fixed in 0.1.2

**Closed** 2018-01-05 14:46 UTC

**Comment by axtho** [comment] 2018-01-05 20:07
I am on OS X 10.12.6 ... thanks for all that work. I know that you would not need to maintain this polyfill, so thanks for that work :) It helps to finally see a light at the end of the i18n Angular tunnel. We have been waiting a long time for this ... at some point I got so frustrated with this to even consider another JS framework :) Anyway, keep up the good work.

**Comment by ocombe** [comment] 2018-01-05 20:50
Yes I know how you feel, it was hard ton convince google that it was necessary because they don't need it internally...
We have many good features on the todo list coming this year, but it always take longer than expected to release them...
