### ISSUE TITLE
Problem with file pattern src/app/**/*.ts to get all ts files whatever the depth

### ISSUE THREAD

**Issue by templth** [ngx-translate/i18n-polyfill#6] opened 2017-12-24 11:11 UTC
When using the following command:

```bash
ngx-extractor -i src/app/**/*.ts -f xlf -o src/assets/i18n/source.xlf
```

I expect the command to handle all files with the extension `ts` in all folders under the `src/app` one whatever the depth. In my case, it only gets the file under direct subfolders of the `src/app` one.

I investigated a bit the problem but can't see option for this in the `yargs` library. It should be directly the case (every sub folders whatever the depth with the pattern `src/app/**/*.ts`.

Any idea? Thanks!

**Comment by vqoph** [comment] 2017-12-28 13:14
Hi, i had the same issue.
adding to the pattern solved the issue in my side : 
`ngx-extractor -i "src/**/*.ts" -f xlf -o src/locale/messages.xliff`

**Comment by BSchuhmacher** [comment] 2018-01-02 05:31
I think it is a duplicate of issue #2 (https://github.com/ngx-translate/i18n-polyfill/issues/2)

**Comment by ocombe** [comment] 2018-01-02 08:13
I added quotes in the readme :)

**Closed by ocombe** 2018-01-02 08:13 UTC
